### ISSUE TITLE
"lt git squash" runs a wrong command at the end of the file

### ISSUE THREAD

**Issue by pascal-klesse** [lenneTech/cli#9]
lt git squash runs the "git commit --am" command and not squash my commits

**Comment by kaihaase** [comment]
The script works and uses the correct commands, see https://gist.github.com/patik/b8a9dc5cd356f9f6f980.

After a soft reset, the changes should be applied to complete the squash.

If something went wrong, it could have been due to a wrong base branch. Please check it and then let me know so I can either fix an existing bug or close this issue.
